### ISSUE TITLE
Document where we are so far.

### ISSUE THREAD

**Issue by blueridanus** [areweguiyet/areweguiyet#1]
A number of potential approaches to GUI, potential problems and potential solutions have been raised in discussion. Those need to be documented for reference.

**Comment by shivshank** [comment]
We could perhaps create a file such as `gui_concerns.md` that collects and summarizes these issues. 

Some topics and questions I've seen come up so far:

  - is the use of a scripting language or DSL justified?
    - leads to discussions of overhead, iteration time, code generation/reflection/introspection and barriers to entry
  - what about html/css vs other formats and methods for describing layout?
  - event flow: callbacks, futures, streams, oh my
  - imperative vs retained state API

I think it's best to present everything as a discussion of the various options (as opposed to "choosing" what we think are the best trade offs to make, since everyone will ultimately disagree).

**Comment by pythoneer** [comment]
I think it would be a good idea to list (mostly) everything we have so far and try to categorize it and try to look what background the project has. But i don't know really how to start. Should me make one tracking issue and several others for every one to discuss it? I have list with some projects worth looking at https://github.com/pythoneer/areweguiyet/wiki but i think we need to dig in there as a starting point.

**Comment by pythoneer** [comment]
This sounds great. I would start to process the list and turn it into issues. I am just wondering how to effectively collect a "result". I could imagine two ways that would on how to actually create an end result on the page. The main problem with collecting stuff inside the issue is that the information gets scattered across multiple post inside of it. So either we have wiki page for each issue in which we constantly collect and update information as we go and turn it into content for the webpage if we feel confident. The other way would just start out corresponding PR's. I think creating PR's is the appropriate way.

So that leads me to the question how do i actually crate content? How far is your tool or should we start by manually crate content to start. What exactly do i have to do to make this happen. I glimpsed over the website code and i would guess the `ecosystem.json` looks like the right place.

**Comment by shivshank** [comment]
The tool is not very far along. I will try to improve it a little more this week, hopefully. There are a few crates that should help with making CLIs, and I would like to try them out.

I think in addition to what is there already, below are some examples of how we can extend `ecosystem.json`:

```typescript
{
    name: String,
    description: Option<String>,
    docs: Option<String>,
    // leave this repo blank if you want to pull information from crates.io
    repo: Option<String>,
    // specify a list of a tags that are relevant for searching through GUI crates
    tags: Vec<String>,
    // new stuff:

    // We may want to enforce that these follow some kind of pattern, i.e, official links only for each
    // chat platform, like discord.gg for Discord, for instance
    chats: Vec<String>,

    // A paragraph that appears in the card following the crates.io description
    // (will get cut off if it is too long, and there will be a "read more" button)
    extended_description: Vec<String>,

    // use cases described in bullet points
    use_cases: Vec<String>,

    // these will become a list of bullet points
    pros: Vec<String>,
    cons: Vec<String>,

    // see my earlier post for what this enum could support
    status: ProjectStatus,

    last_updated: String,
}
```

`ecosystem.json` is the correct place to make the changes for now. Once the changes are made, doing `cargo run` from the cli directory **should** "just work," although I know it failed for at least one person. It is not very robust.

I agree that information will get scattered in issues. PRs should work well, since the `ecosystem.json` should be easy enough to read, assuming it is formatted well. PRs will allow people to comment easily on changes.
