### ISSUE TITLE
Remove imgui-rs

### ISSUE THREAD

**Issue by dxenonb** [areweguiyet/areweguiyet#25]
Proposing possible removal of IMGUI-RS as it looks unmaintained and unused.

Removal may not be the most appropriate action though?

https://github.com/lucidscape/imgui-rs

**Comment by pythoneer** [comment]
I see the problem. I think we need to have some kind of policy what constitutes a "rightful" removal of a library. I think we have discussion multiple times in the near future as more and more toolkits enter a "usable" state and get promoted here but a re abandoned later anyway. So i think we could use this as an opportunity to establish something that could help identify libraries that needs to be removed from AWGY that is transparent to everyone outside the project to prevent us and others from arbitrariness. You can imagine cases where "a good friend of ours" has a mediocre library that is barely maintained on AWGY but a different library that is objectively "better" (we need to establish what "better" constitutes) but is removed anyway because the maintainer is not "such a good friend of ours" (i hope the idea is getting across)

By having more defined guidelines about:
    - what does a library need to be on the AWGY list
    - what makes a library on the AWGY list a candidate of removal.

(maybe find other things that need better criteria for actions to not came across arbitrary in our decisions)

So to start of a little brainstorming: does 
    - imgui-rs work? 
    - is it still up to date (with the "original c library")?
    - does it even need maintenance?

If a library is unmaintained but still functioning well, does this constitutes a removal or do we have better options like, marking it "unmaintained"? If it does not constitutes a removal, what circumstances does?

**Comment by tesselode** [comment]
Forgive me if I'm misunderstanding, but I think the imgui-rs that the site links to is [this one](https://github.com/Gekkio/imgui-rs), which is quite actively maintained.
