### ISSUE TITLE
Can I contribute my library to areweguiyet?

### ISSUE THREAD

**Issue by floers** [areweguiyet/areweguiyet#61]
I am currently working on a library to improve GTK app development with rust [here](https://gitlab.com/loers/gstore). I'd like to place it here to make others aware of it if thats possible.

If you think my library is of any interes I would like to contribute it as stated in the Contribution section in the readme.

**Comment by madsmtm** [comment]
Hey @floers, sorry for the long delay, I hope you're still available.

I took a look at your crate, and while I get the desire for wanting publicity for your crate, I can't really see the direct value that it provides specifically for _GUI_ development?

It seems to me that you may be better served by contacting the gtk-rs folks, and getting publicity through their websites, since `gstore` _is_ fundamentally tied to GTK, and your most likely users would probably come from people who have already decided to build their application using GTK, not from users who are just starting out?

Or perhaps I'm mistaken?
